# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopUpSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopUpSwiftUI
  pod 'ExytePopupView'

end
